name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.5
            gemfile: Gemfile
          - ruby: 2.6
            gemfile: Gemfile
          - ruby: 2.7
            gemfile: Gemfile
          - ruby: 3.0.5
            gemfile: Gemfile
          - ruby: 3.1
            gemfile: Gemfile
          - ruby: 3.2
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: gemfiles/simplecov_1.gemfile
          - ruby: 3.4
            gemfile: gemfiles/simplecov_1.gemfile
          - ruby: 4.0
            gemfile: gemfiles/simplecov_1.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec
    - name: Run Rubocop
      run: bundle exec rubocop
